# Generated by Django 2.1.1 on 2020-09-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=45, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('address', models.CharField(max_length=45, null=True)),
                ('photo', models.ImageField(default='', upload_to='')),
                ('subscribers', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('is_premium', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=45, null=True)),
                ('sns1', models.CharField(max_length=45, null=True)),
                ('sns2', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('running_time', models.CharField(max_length=45, null=True)),
                ('break_time', models.CharField(max_length=45, null=True)),
                ('closed_on', models.CharField(max_length=15, null=True)),
                ('num_menu', models.IntegerField(null=True)),
                ('locality', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=45, null=True)),
                ('category', models.IntegerField(null=True)),
            ],
        ),
    ]
