# Generated by Django 3.1.1 on 2020-09-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, null=True)),
                ('longitude', models.IntegerField(null=True)),
                ('latitude', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=45, null=True)),
                ('photo', models.ImageField(null=True, upload_to=None)),
                ('subscribers', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('is_premium', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=45, null=True)),
                ('sns1', models.CharField(max_length=45, null=True)),
                ('sns2', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('running_time', models.CharField(max_length=45, null=True)),
                ('break_time', models.CharField(max_length=45, null=True)),
                ('closed_on', models.CharField(max_length=15, null=True)),
                ('num_menu', models.IntegerField(null=True)),
                ('locality', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=45, null=True)),
                ('category', models.IntegerField(null=True)),
            ],
        ),
    ]
