# Generated by Django 3.1.1 on 2020-09-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='photo',
        ),
    ]
