# Generated by Django 3.1.1 on 2020-09-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200911_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_premium',
        ),
    ]
