# Generated by Django 2.1.5 on 2020-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_store_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_premium',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
