# Generated by Django 2.1.1 on 2020-09-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200911_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='username',
            new_name='storename',
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
