# Generated by Django 2.1.1 on 2020-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200920_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='주소없음', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
