# Generated by Django 2.1.1 on 2020-10-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0009_auto_20200922_2326'),
        ('store', '0006_auto_20200920_2215'),
        ('customer', '0007_auto_20200920_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('purchased', models.DateTimeField(auto_created=True)),
                ('last_used', models.DateTimeField(auto_created=True)),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('start_date', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('cycle', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('purchased_type', models.IntegerField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
