# Generated by Django 2.1.1 on 2020-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0003_auto_20201016_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='cycle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='purchased_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
