# Generated by Django 2.1.1 on 2020-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0004_auto_20201022_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='purchased',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='remain',
            field=models.IntegerField(null=True),
        ),
    ]
