# Generated by Django 2.1.1 on 2020-10-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublist', '0006_remove_subscribes_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribes',
            name='remain',
            field=models.IntegerField(null=True),
        ),
    ]
