# Generated by Django 2.1.1 on 2020-09-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
