# Generated by Django 2.1.1 on 2020-10-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201019_2126'),
        ('customer', '0008_administrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrator',
            new_name='Manager',
        ),
    ]
