# Generated by Django 2.1.1 on 2020-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20201023_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.CharField(default='admin@subserve.com', max_length=45),
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='qweqwe123', max_length=15),
        ),
    ]
