# Generated by Django 2.1.1 on 2020-09-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_store_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subscribes',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='subscribes',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='subscribes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='store_id',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Subscribes',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
