# Generated by Django 2.1.1 on 2020-10-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200920_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
