# Generated by Django 3.1.1 on 2020-09-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('price', models.IntegerField(null=True)),
                ('photo', models.CharField(max_length=45, null=True)),
                ('allergic', models.CharField(max_length=45, null=True)),
                ('subscribers', models.IntegerField(null=True)),
                ('cycle', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('last_subscribers', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('in_event', models.BooleanField(null=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
