# Generated by Django 2.1.1 on 2020-09-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200922_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store_id',
        ),
    ]
