# Generated by Django 2.1.1 on 2020-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rank',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
