# Generated by Django 2.1.1 on 2020-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menu_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
