# Generated by Django 2.1.1 on 2020-10-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20201025_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='last_subscribers',
        ),
    ]
