# Generated by Django 2.1.1 on 2020-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_menu_last_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='last_subscribers',
            field=models.IntegerField(null=True),
        ),
    ]
