# Generated by Django 2.1.1 on 2020-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menu_last_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
