# Generated by Django 2.1.1 on 2020-10-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20201025_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='subscribers',
        ),
    ]
