# Generated by Django 2.1.1 on 2020-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_remove_menu_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='subscribers',
            field=models.IntegerField(null=True),
        ),
    ]
